### ISSUE TITLE
use blinker

### ISSUE THREAD

**Issue by phanirithvij** [rmartin16/qbittorrentui#13]
blinker-alt is unmaintained (pypy has 2017 as the last release)

https://github.com/pallets-eco/blinker

I've replaced blinker-alt in pyproject.toml with `blinker ==1.8.2` and the code works as before.

**Comment by rmartin16** [comment]
Thanks for letting me know. I published [v0.3.6](https://github.com/rmartin16/qbittorrentui/releases/tag/v0.3.6) using blinker instead of blinker-alt.
