### ISSUE TITLE
Pseudocode operator on line 76 in file application.py

### ISSUE THREAD

**Issue by marshall-brown** [rmartin16/qbittorrentui#5]
https://github.com/rmartin16/qbittorrentui/blob/43c224b94ed9564f333acb7910d3508e53e2552f/qbittorrentui/windows/application.py#L76

![image](https://user-images.githubusercontent.com/43415868/154168269-0132df42-3330-46d1-96e7-5e72a3211425.png)

Running on WSL
![image](https://user-images.githubusercontent.com/43415868/154168370-c08ab1d6-550e-4506-9989-f9a79e79bd01.png)

**Comment by marshall-brown** [comment]
Let me know if you allow PRs :)

**Comment by rmartin16** [comment]
Hi @marshall-brown,
That's the walrus operator; it was [introduced](https://realpython.com/python-walrus-operator/) in Python 3.8....more or less for this specific scenario. Python 3.6 will definitely get upset about it though; try it with 3.8 or newer and you should be good to go. (FWIW, I recommend [pyenv](https://github.com/pyenv/pyenv) for simple management of multiple python versions.)

**Comment by marshall-brown** [comment]
Ill upgrade test and report back
