### ISSUE TITLE
Add emoji to UI interface, ALL, DOWNLOADING, COMPLETED etc

### ISSUE THREAD

**Issue by plasmoduck** [rmartin16/qbittorrentui#6]
Hi mate, what piece of source do I have to edit to change the names of ALL, DOWNLOADING, COMPLETED, PAUSED, ACTIVE etc to add some emoji for visual asthetics?

**Comment by rmartin16** [comment]
If you're talking about the names of the "tabs" at the top, you should be able to add those in [TorrentListTabsColumns](https://github.com/rmartin16/qbittorrentui/blob/master/qbittorrentui/windows/torrent_list.py#L680).

**Comment by plasmoduck** [comment]
Thanks, now how to compile?

**Comment by rmartin16** [comment]
To use it, just install wherever your running `qbittorrentui` from with `python -m pip install -e /path/to/modified/source`

**Comment by plasmoduck** [comment]
Thanks
